### PR TITLE
V22.5

### PR DESCRIPTION
**Pull request by franck-boullier**
# Improvement:

Use the custom function `push` instead of the native function `alambda_simple`
Tests done in the DEV/Staging for the following lambda calls:
- lambda_create_user PASSED
- lambda_update_user_profile PASSED
- ut_create_unit PASSED
- lambda_add_user_to_role_in_unit_with_visibility PASSED
- ut_remove_user_from_unit PASSED
- ut_update_user PASSED

# Bug fix:

Make sure the field to store lambda calls is big enough

### CODE REVIEW

**Comment by franck-boullier** [comment]
@kaihendry this has been tested in the DEV/Staging and this seem to be working as expected.

I need you to tell me if it's OK to roll this into the other environments:
- DEMO
- PROD

The main concern I have is to know if the DEMO and PROD environment have already been configured to be able to use the new **push** custom function that you have created as a drop in replacement for the **alambda_simple**

Once I have @kaihendry's confirmation that the DEMO and PROD environment are capable of handling this upgrade I will upgrade the DB schema for the UNTE Db in both the DEMO and the PROD environment.

**Comment by kaihendry** [comment]
I expect 5 lines to change, not 11k.

```
bugzilla/lambda_notification_case_invited.sql:  CALL mysql.lambda_async(CONCAT('arn:aws:lambda:ap-southeast-1:812644853088:function:push')
bugzilla/lambda_notification_case_new.sql:      CALL mysql.lambda_async(CONCAT('arn:aws:lambda:ap-southeast-1:812644853088:function:push')
bugzilla/lambda_notification_case_updated.sql:  CALL mysql.lambda_async(CONCAT('arn:aws:lambda:ap-southeast-1:812644853088:function:push')
bugzilla/lambda_notification_message_new_comment.sql:   CALL mysql.lambda_async(CONCAT('arn:aws:lambda:ap-southeast-1:812644853088:function:push')
bugzilla/lambda_notification_case_assignee_updated.sql: CALL mysql.lambda_async(CONCAT('arn:aws:lambda:ap-southeast-1:812644853088:function:push')
```

**Comment by franck-boullier** [comment]
> I expect 5 lines to change, not 11k.

don't concern yourself with that @kaihendry <--- this is a side effect of how some files are handled in this repo (not perfect but that's the best solution we have today)

The only answer I need from you @kaihendry is the answer to the question
> [Have] the DEMO and PROD environment (...) already been configured to be able to use the new **push** custom function that you have created as a drop-in replacement for the **alambda_simple** function?

**Comment by franck-boullier** [comment]
> I expect 5 lines to change

These have been changed. See https://github.com/unee-t/enterprise_database/pull/7/files#diff-59282da524bc4e57c31e8c44620da6ea

**Comment by kaihendry** [comment]
The new **push** function has been deployed to all environments now. It just needs testing.

Code is here: https://github.com/unee-t/lambda2sns/tree/lambda2sqs_push

**Comment by franck-boullier** [comment]
DEMO environment has ben upgraded to v22.5 of the DB schema so we can do more tests

**Comment by franck-boullier** [comment]
DEV/Staging and DEMO envos have been updated to use `ut_lambda2sqs_push` as the name of the function

**Comment by franck-boullier** [comment]
Deployed in the PROD - No issue during upgrade

**Pull request merged**
